### ISSUE TITLE
Unit 1-5

### ISSUE THREAD

**Issue by willcyber** [willcyber/fastpages#10]
2.7+/3

[Unit 1-5 notes](https://willcyber.github.io/fastpages/tri2/2022/12/01/vocab.html)

<html>
<body>

Unit | Score
-- | --
Unit 1 | 0.95/1
Unit 2 | 1/1
Unit 3 | 1/1
Unit 4 | 0.9/1
Unit 5 | 1/1

</body>
</html>

4.85/5

**Comment by lwu1822** [comment]
2.7+/3: Explains vocab within code examples
