### ISSUE TITLE
William Wu Final Project - Average Score 18.67/20

### ISSUE THREAD

**Issue by willcyber** [willcyber/fastpages#13]
Average Score 18.67/20

<html>
<body>

Night of the Museum or Friday in Class before break. | 5 | Individual Attendance, Capture the Moment: 2 pointsTeam Presentation to Teacher: 3 points (1 minute),FrontendBehind the scenesCross DomainFE/BE DebuggingJWTDatabase
-- | -- | --
Live Review with student crossover | 10 | Individual Score for Runtime (binary criteria below, 5 points)Project quality, running cross domain and no crashes on FE to BE with these reviewsUI contains inputs that are validated for garbage, data cleaned (ie validate DOB or Password)UI contains actions for Create, Read,UI contains actions for Update, DeleteJWT is guarding a feature, demonstration of cookiesIndividual Score for Code Review (binary criteria below,  5 points) Project quality, observation of comments in every function, class, or method reviewed.  Be sure to review POJO, API Controller, and JPA.BE contains and API that shows that it handles error conditions (ie duplicate user id)BE contains support for GET and POST methodsBE contains a database that supports Create, ReadBE contains a database that supports Update, Delete
Silent Review | 5 | Team review ticket 3 points. .5 per bulletPurpose/Theme/Quality.VideoRuntime LinksREADME.mdBlog, Guides for review75% of individuals have met full stack work.Individual Review Ticket 2 points.   Provide me individual review ticket that is linked from Team Summary.  Highlight your accomplishments.. Quality of Presentation .5 per bulletIndividual Review TicketRuntime LinksTechnical AccomplishmentsBlog, Guides for reviewMeeting full stack and backend objectivesGitHub analytics

</body>
</html>

<html>
<body>

Items | Self | Andrew | Ritvik | Average
-- | -- | -- | -- | --
Individual Attendance Capture the Moment | 2 | 2 | 2 | 2
Team Presentation to Teacher: Behind the Scenes: | 3 | 3 | 3 | 3
Project quality, running cross domain and no crashes on FE to BE with these reviews | 1 | 1 | 1 | 1
UI contains inputs that are validated for garbage, data cleaned (ie validate DOB or Password) | 1 | 1 | 1 | 1
UI contains actions for Create, Read | 1 | 1 | 1 | 1
UI contains actions for Update, Delete | 1 | 1 | 1 | 1
JWT is guarding a feature, demonstration of cookies | 1 | 1 | 1 | 1
(Backend) Project quality, observation of comments in every function, class, or method reviewed. | 1 | 1 | 1 | 1
BE contains and API that shows that it handles error conditions (ie duplicate user id) | 1 | 1 | 1 | 1
BE contains support for GET and POST methods | 1 | 1 | 1 | 1
BE contains a database that supports Create, Read | 1 | 1 | 1 | 1
BE contains a database that supports Update, Delete | 1 | 1 | 1 | 1
Team Review | 2 | 2 | 2 | 1.83
Silent Review | 1.5 | 1.5 | 2 | 1.5
TOTAL SCORE | 18.5 | 18.5 | 19 | 18.67

</body>
</html>

## Purpose/Theme
- The theme of our project is ciphers. We created the project to allow users to learn and practice decrypting ciphers. We also have decryptors that users can use to decrypt ciphers they have and an option for them to save their cipher.

## Runtime Links
- [Frontend](https://lwu1822.github.io/crimebustersrevival/)
- [Backend](https://crimebusters.tk/)

## Technical Achievement
findEmail endpoint that takes information from the frontend cookie to figure out who the user is

Create backend for the ciphers

![image](https://user-images.githubusercontent.com/57081237/221945939-efab4931-7d31-4c0a-8e21-77773b1393ec.png)

![image](https://user-images.githubusercontent.com/57081237/221945573-c2d59470-8882-47a1-a655-2b3ef73daa1f.png)

Log ciphers and paste it in history

![image](https://user-images.githubusercontent.com/57081237/221945270-97bd2cef-5a72-4942-9505-5c010a4c0ea8.png)

## Github analytics
[Frontend](https://github.com/lwu1822/crimebustersrevival/graphs/contributors)
[Backend](https://github.com/lwu1822/codebusters/graphs/contributors)

**Comment by supermengman** [comment]
Night at the Museum: 5/5
- pictures of behind the scenes
- frontend/backend debugging after server went down

Live Review:
Individual Score for Runtime: 5/5
- no crashing
- validate password matching
- create/read user
- update/delete users
- jwt for login

Code Review: 5/5
- comments in functions reviewed
- error handling/exception handling in API controllers that return custom errors
- GET/POST for decrypting
- database CRUD

Silent Review:
Team Review: 2/3
- purpose/quality inside readme.md
- runtime links 
- full stack most individuals

Individual Review: 1.5/2
- review ticket exists
- runtime links
- full stack/backend objectives

Total: 18.5/20

**Comment by Ritvik-Keerthi** [comment]
Night of the Museum- 5/5
Individual score for runtime - 5/5

runs very smoothly
Data is clear
CRUD stuff met
JWT login token is good
Individual Score for Code Review - 5/5

Project has very good quality
Handling error criteria is met
BE contains GET and POST
CRUD met
Crossover Grade - 10/10

Final Score: 20/20
