### ISSUE TITLE
William and Aidan Review Ticket

### ISSUE THREAD

**Issue by willcyber** [willcyber/fastpages#14]
[William Hacks](https://willcyber.github.io/fastpages/tri3/2023/03/13/datahacks.html)
[Aidan Hacks](https://aidanywu.github.io/fastpages/jupyter/2023/03/13/datatypes.html)

William MC
![image](https://user-images.githubusercontent.com/57081237/224766367-d20e8d30-9c23-47bd-96d9-e40d3a8b504a.png)
8. Accidently thought the array index starts at 1. B would be correct if it starts at 0, which is does.
9. Didnt realize Math.random includes 0. You would needa add 1 for each dice if that is the case

**Comment by lwu1822** [comment]
Crossover review: 0.9/1
* Completed MC with corrections
* Each part of hack is answered/completed
* Chose 2017 FRQ
* Could update theme on fastpages
