### ISSUE TITLE
Primitives

### ISSUE THREAD

**Issue by willcyber** [willcyber/fastpages#3]

**Comment by willcyber** [comment]
2.7+/3
Productive Blogging
Create a Jupyter Notebook(s) using IJava to capture key learning on Primitives: [LINK](https://willcyber.github.io/fastpages/jupyter/2022/08/26/Primatives.html)
Create a Jupyter Notebook using Bash to show that you have all the key tools installed: [LINK](https://willcyber.github.io/fastpages/jupyter/2022/08/25/bash.html)
Capture information that will grow to 10 college board units: [LINK](https://willcyber.github.io/fastpages/cb/)

Code.org
![image](https://user-images.githubusercontent.com/57081237/187117066-730f1773-c2cb-4d9d-b1c0-7ad418bdd695.png)

**Comment by lwu1822** [comment]
2.7+
- code.org completed
- Created a calculator using knowledge of primitives
- Bash shows that tools are all installed
- Created a page for CollegeBoard learning
- Room for improvement: Could make blog more organized
