### ISSUE TITLE
Using Objects

### ISSUE THREAD

**Issue by willcyber** [willcyber/fastpages#4]
2.7
Code.org
![image](https://user-images.githubusercontent.com/57081237/188514254-e106f6f4-c350-48d1-a253-49656718d3d7.png)

Link to Code.org takeaways/comments: https://willcyber.github.io/fastpages/jupyter/2022/09/05/code.org-takeaways.html

Link to Menu: https://willcyber.github.io/fastpages/jupyter/2022/09/02/menu.html

**Comment by lwu1822** [comment]
2.7+

- code.org completed with notes taken on objects and extended classes
- Created console with group's calculators
- Created extra calculator
- Suggestions: Maybe make more of your own calculators to add to the console?
