### ISSUE TITLE
Backend Development

### ISSUE THREAD

**Issue by willcyber** [willcyber/fastpages#5]
2.7+
[if else lesson](https://willcyber.github.io/fastpages/jupyter/2022/09/06/if-else-statements.html)
[Deployment on AWS](https://nighthawkwill.tk/)
[Focus and Habits](https://willcyber.github.io/fastpages/jupyter/2022/09/09/Focus-and-Habits.html)

**Comment by lwu1822** [comment]
2.7+
* if else lesson complete, with switch case statements and De Morgan's law
* William did extra by creating a rock paper scissors game within the if else lesson
* Deployment on AWS complete, domian name is accessible
* Focus and Habits has notes from the video as well as goals and list of gratitude
