### ISSUE TITLE
Free Response Question No. 1

### ISSUE THREAD

**Issue by willcyber** [willcyber/fastpages#6]
[FRQ](https://willcyber.github.io/fastpages/jupyter/2022/09/13/aptestprep.html)
[Arrays](https://willcyber.github.io/fastpages/jupyter/2022/09/12/arrays.html)

**Comment by lwu1822** [comment]
2.7
- FRQ completed with corrections and revisions
- 2D Array printed the monkeys horizontally and created a nursery rhyme with different animals
