### ISSUE TITLE
Design Starters

### ISSUE THREAD

**Issue by willcyber** [willcyber/fastpages#7]
[Fibo](https://willcyber.github.io/fastpages/jupyter/2022/09/23/Fibonacci.html)
[Javascript](https://willcyber.github.io/fastpages/jupyter/2022/09/25/javascript.html)
[Design](https://willcyber.github.io/fastpages/jupyter/2022/09/24/programdesign.html)

**Comment by lwu1822** [comment]
2.7
- Fibo done with extends, no abstraction though
- Javascript table created
- Design with wireframes of project
